### ISSUE TITLE
Top BCR modules broken with Bazel 9.0.0rc6 (Updated Jan 16)

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/bazel-central-registry#6402]
## The following modules are broken with Bazel@last_rc:
BCR Bazel Compatibility Test:  https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748
### gazelle@0.47.0
Maintainers:  @fmeum, @linzhp, @tyler-french
- [gazelle@0.47.0 - :darwin: macOS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc535-8cca-406f-a0c0-5c9e5b1b8001)
- [gazelle@0.47.0 - :ubuntu: Ubuntu 20.04 LTS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8189-4c95-8820-d4a6717ac229)
- [gazelle@0.47.0 - :windows: Windows - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-818a-4b1e-abd2-3b65d2f64363)
### googleapis@0.0.0-20260109-6145b5ff
Maintainers:  @diegomarquezp, @scotthart, @mpeddada1, @jinseopkim0
- [googleapis@0.0.0-20260109-6145b5ff - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8199-4770-96f4-67cfd58e4b72)
- [googleapis@0.0.0-20260109-6145b5ff - :darwin: macOS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc534-cd24-4e34-be5a-0149ef6843d0)
- [googleapis@0.0.0-20260109-6145b5ff - :ubuntu: Ubuntu 20.04 LTS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-819c-4ddd-8077-6f49ddf69478)
- [googleapis@0.0.0-20260109-6145b5ff - :windows: Windows - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-819d-4e37-8e01-2c5067486ece)
### grpc@1.78.0-pre1
Maintainers:  @pawbhard, @rishesh007, @markdroth, @sergiitk, @yuanweiz, @asheshvidyut, @sreenithi
- [grpc@1.78.0-pre1 - :debian: Debian 11 Bullseye (OpenJDK 17, gcc 10.2.1) - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81a4-44c8-9330-1618b22d8b9e)
- [grpc@1.78.0-pre1 - :darwin: macOS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc535-216f-4b9f-b95e-3f67db22cf7a)
- [grpc@1.78.0-pre1 - :darwin: macOS arm64 - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc531-cfd8-48c9-b55d-079a0d7a283e)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 20.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81a8-4435-8f6f-3822a2c3381a)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 22.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81a9-4ef3-a5da-b6bd5e0c9686)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 24.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81aa-48f7-bf82-c60cc903ecbb)
- [grpc@1.78.0-pre1 - :debian: Debian 11 Bullseye (OpenJDK 17, gcc 10.2.1) - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81ab-4445-9bea-1055dd093fc3)
- [grpc@1.78.0-pre1 - :darwin: macOS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc535-a621-4d49-9b80-f314671a7577)
- [grpc@1.78.0-pre1 - :darwin: macOS arm64 - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc531-e78a-48e5-a4de-322241d33257)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 20.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81af-4de6-a22b-852d37a00e17)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 22.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81b1-44e5-b04d-ce0c829fc4b4)
- [grpc@1.78.0-pre1 - :ubuntu: Ubuntu 24.04 LTS - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81b2-456e-8373-98568e1a344f)
- [grpc@1.78.0-pre1 - :windows: Windows - ](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81b3-4bef-9844-3cd3a56b397b)
### jsoncpp@1.9.6
Maintainers:  @bazelbuild/bcr-maintainers
- [jsoncpp@1.9.6 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81be-4ffe-8634-805efca85d22)
- [jsoncpp@1.9.6 - :darwin: macOS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc535-b0e5-48c7-a593-64071858850b)
- [jsoncpp@1.9.6 - :darwin: macOS arm64 - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc532-4f5a-4b4a-9269-60fbde815f67)
- [jsoncpp@1.9.6 - :ubuntu: Ubuntu 20.04 LTS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81c1-46f6-9353-0eec5f2047b9)
- [jsoncpp@1.9.6 - :windows: Windows - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81c2-4d07-a676-b9df7eea0626)
### libpfm@4.11.0.bcr.1
Maintainers:  @bazelbuild/bcr-maintainers
- [libpfm@4.11.0.bcr.1 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81c4-40b6-b3be-ac054da24576)
- [libpfm@4.11.0.bcr.1 - :rocky: Rocky Linux 8 - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81c5-46e1-9cfe-90cb52e2af81)
- [libpfm@4.11.0.bcr.1 - :ubuntu: Ubuntu 20.04 LTS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81c6-454f-b28b-653bdcb8c585)
### openssl@3.5.4.bcr.0
Maintainers:  @illicitonion, @UebelAndre
- [openssl@3.5.4.bcr.0 - :windows: Windows - Build and test](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81ef-416a-976b-c96c43622cc7)
- [openssl@3.5.4.bcr.0 - :windows: Windows arm64 - Build and test](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-81f0-40fb-9032-c46437c9fafb)
### rules_apple@4.3.3
Maintainers:  @keith, @brentleyjones, @luispadron, @aaronsky, @adincebic
- [rules_apple@4.3.3 - :darwin: macOS arm64 - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc532-f03f-40af-acb7-44a76db4990c)
### rules_buf@0.5.2
Maintainers:  @bcr-buf
- [rules_buf@0.5.2 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8225-4fc2-bf6b-a72a837ccd9e)
- [rules_buf@0.5.2 - :darwin: macOS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc537-91e6-4db4-a5b5-59c2bf6ba0fa)
- [rules_buf@0.5.2 - :ubuntu: Ubuntu 20.04 LTS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8229-43b6-af34-2d0d5f8b6996)
### rules_erlang@3.16.0
Maintainers:  @HoloRin
- [rules_erlang@3.16.0 - :darwin: macOS - Verify build targets (macos)](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc543-6f18-40da-ad1b-a5242460b3dd)
- [rules_erlang@3.16.0 - :ubuntu: Ubuntu 20.04 LTS - Verify build targets (ubuntu2004)](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8237-4cf9-92f1-859beca8459f)
### rules_jvm_external@6.9
Maintainers:  @jin, @shs96c, @cheister
- [rules_jvm_external@6.9 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-825b-4360-8916-18b0ee3a40eb)
- [rules_jvm_external@6.9 - :darwin: macOS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc538-6030-422b-a66a-0a65a9da2035)
- [rules_jvm_external@6.9 - :darwin: macOS arm64 - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc533-5166-47c7-b5fd-322d5b26948d)
- [rules_jvm_external@6.9 - :ubuntu: Ubuntu 20.04 LTS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-825f-425e-8632-4ad07ffcc5bb)
- [rules_jvm_external@6.9 - :windows: Windows - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8261-420e-a814-2015bd5eb318)
- [rules_jvm_external@6.9 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8262-4a1d-b6ac-a262f370d6aa)
- [rules_jvm_external@6.9 - :darwin: macOS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc539-0bf6-4642-a12a-ac565dc7d523)
- [rules_jvm_external@6.9 - :darwin: macOS arm64 - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc533-b4ee-4905-8dba-b7e977dbce5a)
- [rules_jvm_external@6.9 - :ubuntu: Ubuntu 20.04 LTS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8267-4cd9-9f5c-34693b1886d7)
- [rules_jvm_external@6.9 - :windows: Windows - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-8268-48c6-92ad-8ee42fb51903)
### rules_kotlin@2.2.2
Maintainers:  @Bencodes, @restingbull, @nkoroste
- [rules_kotlin@2.2.2 - :darwin: macOS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc538-a043-4c43-93ea-cd669c203cee)
- [rules_kotlin@2.2.2 - :ubuntu: Ubuntu 20.04 LTS - Verify build targets](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-826a-4cc2-a6a0-62cbf9479f7c)
### toolchains_protoc@0.6.1
Maintainers:  @alexeagle
- [toolchains_protoc@0.6.1 - :debian: Debian 10 Buster (OpenJDK 11, gcc 8.3.0) - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-82cb-4b51-84c8-96fb951e1666)
- [toolchains_protoc@0.6.1 - :darwin: macOS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc53b-2737-468e-a0f2-49b697c7040b)
- [toolchains_protoc@0.6.1 - :ubuntu: Ubuntu 20.04 LTS - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-82ce-434e-8430-28a5a8769244)
- [toolchains_protoc@0.6.1 - :windows: Windows - Run test module](https://buildkite.com/bazel/bcr-bazel-compatibility-test/builds/748#019bc52d-82d0-4ccc-b49d-9e77e4d6f4e4)

**Comment by hofbi** [comment]
@meteorcloudy Since yesterday we have https://github.com/bazel-contrib/bazelrc-preset.bzl/releases/tag/v1.5.1 which comes with https://github.com/bazel-contrib/bazelrc-preset.bzl/commit/373111947cbcb44f7f92c48aca806e4e80241f40. Checking the diff of bazel-lib, https://github.com/bazel-contrib/bazel-lib/commit/165451f74989eb331d6bededc809ea64aaccfa95 seems to be included now so Bazel 9 should work with the latest release.

**Comment by meteorcloudy** [comment]
@hofbi Sounds great, I will update this issue regularly based on latest result.

**Comment by rsc** [comment]
https://github.com/bazelbuild/bazel-central-registry/pull/6424 adds a new re2 version that should fix the errors shown above for re2.

**Comment by mattyclarkson** [comment]
`toolchain_utils@1.3.0` (as far as we know) should be good for Bazel 9. The failure is an infra failure for `8.x`:

```
Downloading https://releases.bazel.build/8.4.2/release/bazel-8.4.2-linux-x86_64...
Downloading: 3 MB out of 61 MB (5%)
2025/11/06 05:14:43 could not download Bazel: failed to download bazel: failed to download bazel: could not copy from https://releases.bazel.build/8.4.2/release/bazel-8.4.2-linux-x86_64 to /var/lib/buildkite-agent/.cache/bazelisk/downloads/_tmp/download2263072035: stream error: stream ID 1; INTERNAL_ERROR; received from peer
```

**Comment by meteorcloudy** [comment]
Indeed, rerun worked, sorry for the noise.

**Comment by UebelAndre** [comment]
For openssl I think the issue is actually a bug in Bazel 9: https://github.com/raccoons-build/bazel-openssl-cc/pull/45#issuecomment-3499772102

@fmeum curious what your thoughts are on that comment.

**Comment by luispadron** [comment]
apple_support should be fixed as of: https://github.com/bazelbuild/apple_support/releases/tag/1.24.4

**Comment by keith** [comment]
rules_swift hopefully fixed by https://github.com/bazelbuild/bazel-central-registry/pull/6479

**Comment by davidben** [comment]
boringssl should be fixed by https://github.com/bazelbuild/bazel-central-registry/pull/6481

(It was just an issue in the example module so, as far as I know, it would not have impacted anything downstream.)

**Comment by fmeum** [comment]
rules_go and Gazelle should be fixed in their latest releases

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/pull/27593 (removing autoloads for rules_cc) only made it into rc2, so unfortunately there are more breakages. I updated the issue with the latest result. rules_swift and gazelle are still broken..

**Comment by Vertexwahn** [comment]
There is now a doctest@2.4.12.bcr.1 version that should fix the issues

**Comment by aignas** [comment]
A new `rules_python` release candidate on BCR should also fix the issues I think.

**Comment by cgrindel** [comment]
[cgrindel_bazel_starlib 0.28.0](https://github.com/cgrindel/bazel-starlib/releases/tag/v0.28.0) should now work with Bazel 9.0.0rc3.

**Comment by ahumesky** [comment]
Latest rules_android should now be working, e.g. with latest bazel:
https://buildkite.com/bazel/rules-android/builds/4167/steps/canvas?sid=019baf8f-063a-44fe-8a67-607cbf8c151b

**Comment by alexeagle** [comment]
@meteorcloudy not to make more work for you, but is it easy for us to find an updated list to finish burning it down?

**Comment by meteorcloudy** [comment]
I just updated this list with the latest result from https://buildkite.com/bazel/bcr-bazel-compatibility-test

**Comment by meteorcloudy** [comment]
@ahumesky rules_android seems to be broken with rc5, possible due to the protobuf upgrade?

**Comment by wep21** [comment]
I guess test error with boost.detail is not specific to boost.detail but to macos ci platform from this issue.
https://github.com/bazelbuild/bazel/issues/28123

**Comment by cgrindel** [comment]
[rules_bazel_integration_test v0.35.0](https://github.com/bazel-contrib/rules_bazel_integration_test/releases/tag/v0.35.0) should now work with Bazel 9.0.0rc3.

**Comment by ted-xie** [comment]
> [@ahumesky](https://github.com/ahumesky) rules_android seems to be broken with rc5, possible due to the protobuf upgrade?

Yeah, runtime versus protobuf library mismatch:

`Caused by: com.google.protobuf.RuntimeVersion$ProtobufRuntimeVersionException: Detected incompatible Protobuf Gencode/Runtime versions when loading Header: gencode 4.33.4, runtime 4.33.1. Runtime version cannot be older than the linked gencode version.`

We should find a better way to keep these in sync. I think there's a PR in rules_android right now that proposes loading the protobuf libraries from `@com_google_protobuf` instead of Maven, which may work. For now I'll update the Maven dep.

**Comment by ted-xie** [comment]
We've submitted a band-aid fix to rules_android and released https://github.com/bazelbuild/rules_android/releases/tag/v0.7.1, so the next BCR top modules build should hopefully pass (or at least fail for a new reason :) )

**Comment by meteorcloudy** [comment]
Closing this one since Bazel 9 have been released. 

Remaining breakages can still be found on nightly run of https://buildkite.com/bazel/bcr-bazel-compatibility-test. 
Thanks everyone for getting BCR modules ready for Bazel 9!

**Comment by jwnimmer-tri** [comment]
> Closing this one since Bazel 9 have been released.

FYI I'd also suggest un-pinning this issue, so it's not living atop https://github.com/bazelbuild/bazel-central-registry/issues anymore.
